azure:
  keyvault:
    enabled: true
    uri: https://zeusfitkeyvault.vault.azure.net/
    client-id: 2d8fa8cb-5039-451e-affb-47cc67d13736
    client-key: fg_8Q~OINNuI-NCX5LL-NVVlBGQncDIWjsgtccwV
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd
