
spring:
  datasource:
    #url: jdbc:mysql://zeusfit.mysql.database.azure.com:3306/zeusfit?useSSL=true
    #username: SofSec
    #password: Progettissimo1
    url: ${Url-DB}:3306/${name-DB}?useSSL=true
    username: ${DB-username}
    password: ${DB-password}
  jpa:
    show-sql: true
    hibernate:

      ddl-auto: update
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false



server:
  port: 8080

azure:
  keyvault:
    enabled: true
    uri: https://zeusfitkeyvault.vault.azure.net/
    client-id: 2d8fa8cb-5039-451e-affb-47cc67d13736
    client-key: ${{ secrets.CLIENT_SECRET }}
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd
